[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
# убираем предупреждение pytest-asyncio:
asyncio_default_fixture_loop_scope = "function"
